mt6765-common: Add missing vendor.mediatek.hardware.meta
error: vendor/samsung/mt6765-common/Android.bp:18011:1: "meta_tst" depends on undefined module "vendor.mediatek.hardware.meta@1.0".

Change-Id: Ia853861adfa709ce6709792173a06a466a84328e
Signed-off-by: jmpfbmx <jmpf.bmx@gmail.com>